using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.BaseClass.#ProtectedInstanceFieldForBaseClass")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.BaseClass.#PublicInstanceFieldForBaseClass")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.MainClass.#ProtectedInstanceFieldForMainClass")]
[assembly: SuppressMessage("Microsoft.Design", "CA1051:DoNotDeclareVisibleInstanceFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.MainClass.#PublicInstanceFieldForMainClass")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.BaseClass.#_privateInstanceFieldForBaseClass")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.BaseClass.#_privateStaticFieldForBaseClass")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.BaseClass.#InternalInstanceFieldForBaseClass")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.BaseClass.#InternalStaticFieldForBaseClass")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.MainClass.#_privateInstanceFieldForMainClass")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.MainClass.#_privateStaticFieldForMainClass")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.MainClass.#InternalInstanceFieldForMainClass")]
[assembly: SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.MainClass.#InternalStaticFieldForMainClass")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.BaseClass.#ProtectedStaticFieldForBaseClass")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.BaseClass.#PublicStaticFieldForBaseClass")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.MainClass.#ProtectedStaticFieldForMainClass")]
[assembly: SuppressMessage("Microsoft.Usage", "CA2211:NonConstantFieldsShouldNotBeVisible", Scope = "member", Target = "HansKindberg.IntegrationTests.Mocks.MainClass.#PublicStaticFieldForMainClass")]